[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"
authors = ["Yamrc <yamrci@outlook.com>"]
description = "Cross-platform tray lib for gpui"
license = "MPL-2.0"

[workspace.dependencies]
gpui = "0.2.2"
anyhow = "1.0.101"
